name: pi_papers_2021_2
description: Image Processing 2021.2 papers.

publish_to: 'none'

version: 0.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^3.0.8
  image_picker: ^0.8.4+4
  fl_chart: ^0.40.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display.otf

assets:
  - assets/images/prototype/icons/add_img.png
  - assets/images/prototype/icons/edit_img.png
  - assets/images/prototype/icons/field.png
  - assets/images/prototype/icons/home.png
  - assets/images/prototype/icons/img.png
  - assets/images/prototype/icons/levels.png
  - assets/images/prototype/icons/radio_button_selected.png
  - assets/images/prototype/icons/radio_button.png
  - assets/images/prototype/icons/reflection.png
  - assets/images/prototype/icons/right_arrow.png
  - assets/images/prototype/icons/rotation.png
  - assets/images/prototype/icons/scale.png
  - assets/images/prototype/icons/translation.png
  - assets/images/prototype/icons/plus.png
  - assets/images/prototype/icons/minus.png
  - assets/images/prototype/icons/slash.png
  - assets/images/prototype/icons/times.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700